# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20160305_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerequest',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
