# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_auto_20160307_0632'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featurerequest',
            unique_together=set([('title', 'client')]),
        ),
    ]
